services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live_location_app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      # - pnpm-store:/pnpm/store
      # - /app/node_modules
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/live_location_app_db
      KAFKA_BROKER: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - internal_net_live_location # Connects to DBs
      - app_network
    command: tail -f /dev/null

  postgres:
    image: postgres:17
    container_name: live_location_db
    restart: unless-stopped
    ports:
      - "5446:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: live_location_app_db
    volumes:
      - pgdatalivelocationappdb:/var/lib/postgresql/data
    networks:
      - internal_net_live_location # Connects to App

  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - internal_net_live_location # Connects to App

networks:
  internal_net_live_location:
    driver: bridge
  app_network:
    name: oidc-auth-ts_app_network
    external: true

volumes:
  pgdatalivelocationappdb:
  # pnpm-store: